# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs/main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainvertical = QtWidgets.QVBoxLayout()
        self.mainvertical.setObjectName("mainvertical")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchNavButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchNavButton.setDefault(False)
        self.searchNavButton.setFlat(False)
        self.searchNavButton.setObjectName("searchNavButton")
        self.horizontalLayout.addWidget(self.searchNavButton)
        self.directNavButton = QtWidgets.QPushButton(self.centralwidget)
        self.directNavButton.setDefault(False)
        self.directNavButton.setFlat(False)
        self.directNavButton.setObjectName("directNavButton")
        self.horizontalLayout.addWidget(self.directNavButton)
        self.viewFunButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewFunButton.setAutoDefault(False)
        self.viewFunButton.setDefault(False)
        self.viewFunButton.setFlat(False)
        self.viewFunButton.setObjectName("viewFunButton")
        self.horizontalLayout.addWidget(self.viewFunButton)
        self.mainvertical.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainvertical.addWidget(self.line)
        self.dynamicStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.dynamicStack.setObjectName("dynamicStack")
        self.Search = QtWidgets.QWidget()
        self.Search.setObjectName("Search")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Search)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.Search)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.searchInputBox = QtWidgets.QLineEdit(self.widget)
        self.searchInputBox.setInputMask("")
        self.searchInputBox.setText("")
        self.searchInputBox.setMaxLength(32767)
        self.searchInputBox.setObjectName("searchInputBox")
        self.horizontalLayout_12.addWidget(self.searchInputBox)
        self.mangaSearchButton = QtWidgets.QPushButton(self.widget)
        self.mangaSearchButton.setObjectName("mangaSearchButton")
        self.horizontalLayout_12.addWidget(self.mangaSearchButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.searchProgressBar = QtWidgets.QProgressBar(self.widget)
        self.searchProgressBar.setEnabled(True)
        self.searchProgressBar.setProperty("value", 0)
        self.searchProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.searchProgressBar.setTextVisible(True)
        self.searchProgressBar.setInvertedAppearance(False)
        self.searchProgressBar.setObjectName("searchProgressBar")
        self.verticalLayout.addWidget(self.searchProgressBar)
        self.searchResultTable = QtWidgets.QTableWidget(self.widget)
        self.searchResultTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchResultTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchResultTable.setCornerButtonEnabled(False)
        self.searchResultTable.setRowCount(0)
        self.searchResultTable.setColumnCount(2)
        self.searchResultTable.setObjectName("searchResultTable")
        item = QtWidgets.QTableWidgetItem()
        self.searchResultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchResultTable.setHorizontalHeaderItem(1, item)
        self.searchResultTable.horizontalHeader().setStretchLastSection(True)
        self.searchResultTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.searchResultTable)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.searchNextButton = QtWidgets.QPushButton(self.widget)
        self.searchNextButton.setDefault(False)
        self.searchNextButton.setFlat(False)
        self.searchNextButton.setObjectName("searchNextButton")
        self.horizontalLayout_9.addWidget(self.searchNextButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.dynamicStack.addWidget(self.Search)
        self.Direct = QtWidgets.QWidget()
        self.Direct.setObjectName("Direct")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Direct)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.Direct)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.directDownloadErrorLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.directDownloadErrorLabel.setFont(font)
        self.directDownloadErrorLabel.setText("")
        self.directDownloadErrorLabel.setScaledContents(False)
        self.directDownloadErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.directDownloadErrorLabel.setWordWrap(True)
        self.directDownloadErrorLabel.setObjectName("directDownloadErrorLabel")
        self.verticalLayout_2.addWidget(self.directDownloadErrorLabel)
        self.DirectTitle = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DirectTitle.setFont(font)
        self.DirectTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.DirectTitle.setWordWrap(True)
        self.DirectTitle.setObjectName("DirectTitle")
        self.verticalLayout_2.addWidget(self.DirectTitle)
        self.directDownloadInput = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directDownloadInput.sizePolicy().hasHeightForWidth())
        self.directDownloadInput.setSizePolicy(sizePolicy)
        self.directDownloadInput.setAlignment(QtCore.Qt.AlignCenter)
        self.directDownloadInput.setObjectName("directDownloadInput")
        self.verticalLayout_2.addWidget(self.directDownloadInput)
        self.directNextButton = QtWidgets.QPushButton(self.widget_2)
        self.directNextButton.setObjectName("directNextButton")
        self.verticalLayout_2.addWidget(self.directNextButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 0, 0, 1, 1)
        self.dynamicStack.addWidget(self.Direct)
        self.Manga = QtWidgets.QWidget()
        self.Manga.setObjectName("Manga")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Manga)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.Manga)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mangaTitle = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mangaTitle.setFont(font)
        self.mangaTitle.setObjectName("mangaTitle")
        self.verticalLayout_3.addWidget(self.mangaTitle, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectAllMangaButton = QtWidgets.QPushButton(self.widget_3)
        self.selectAllMangaButton.setObjectName("selectAllMangaButton")
        self.horizontalLayout_2.addWidget(self.selectAllMangaButton)
        self.inverseSelectedMangaButton = QtWidgets.QPushButton(self.widget_3)
        self.inverseSelectedMangaButton.setObjectName("inverseSelectedMangaButton")
        self.horizontalLayout_2.addWidget(self.inverseSelectedMangaButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.chapterListWidget = QtWidgets.QListWidget(self.widget_3)
        self.chapterListWidget.setGridSize(QtCore.QSize(0, 20))
        self.chapterListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.chapterListWidget.setModelColumn(0)
        self.chapterListWidget.setUniformItemSizes(True)
        self.chapterListWidget.setWordWrap(True)
        self.chapterListWidget.setSelectionRectVisible(True)
        self.chapterListWidget.setObjectName("chapterListWidget")
        self.verticalLayout_3.addWidget(self.chapterListWidget)
        self.selectedMangaDownloadButton = QtWidgets.QPushButton(self.widget_3)
        self.selectedMangaDownloadButton.setObjectName("selectedMangaDownloadButton")
        self.verticalLayout_3.addWidget(self.selectedMangaDownloadButton)
        self.mangaDataLoadProgressBar = QtWidgets.QProgressBar(self.widget_3)
        self.mangaDataLoadProgressBar.setProperty("value", 24)
        self.mangaDataLoadProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.mangaDataLoadProgressBar.setObjectName("mangaDataLoadProgressBar")
        self.verticalLayout_3.addWidget(self.mangaDataLoadProgressBar)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        self.dynamicStack.addWidget(self.Manga)
        self.Download = QtWidgets.QWidget()
        self.Download.setObjectName("Download")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Download)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.Download)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.progressTitleLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressTitleLabel.setFont(font)
        self.progressTitleLabel.setText("")
        self.progressTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressTitleLabel.setWordWrap(True)
        self.progressTitleLabel.setObjectName("progressTitleLabel")
        self.verticalLayout_4.addWidget(self.progressTitleLabel)
        spacerItem5 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.totalDownloadProgressLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.totalDownloadProgressLabel.setFont(font)
        self.totalDownloadProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDownloadProgressLabel.setWordWrap(True)
        self.totalDownloadProgressLabel.setObjectName("totalDownloadProgressLabel")
        self.verticalLayout_4.addWidget(self.totalDownloadProgressLabel)
        self.totalDownloadProgressBar = QtWidgets.QProgressBar(self.widget_4)
        self.totalDownloadProgressBar.setMinimum(0)
        self.totalDownloadProgressBar.setMaximum(0)
        self.totalDownloadProgressBar.setProperty("value", 0)
        self.totalDownloadProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDownloadProgressBar.setObjectName("totalDownloadProgressBar")
        self.verticalLayout_4.addWidget(self.totalDownloadProgressBar)
        spacerItem6 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.chapterDownloadProgressLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.chapterDownloadProgressLabel.setFont(font)
        self.chapterDownloadProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.chapterDownloadProgressLabel.setWordWrap(True)
        self.chapterDownloadProgressLabel.setObjectName("chapterDownloadProgressLabel")
        self.verticalLayout_4.addWidget(self.chapterDownloadProgressLabel)
        self.chapterDownloadProgressBar = QtWidgets.QProgressBar(self.widget_4)
        self.chapterDownloadProgressBar.setMinimum(0)
        self.chapterDownloadProgressBar.setMaximum(0)
        self.chapterDownloadProgressBar.setProperty("value", -1)
        self.chapterDownloadProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.chapterDownloadProgressBar.setObjectName("chapterDownloadProgressBar")
        self.verticalLayout_4.addWidget(self.chapterDownloadProgressBar)
        spacerItem7 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        self.pageDownloadProgressLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pageDownloadProgressLabel.setFont(font)
        self.pageDownloadProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pageDownloadProgressLabel.setWordWrap(True)
        self.pageDownloadProgressLabel.setObjectName("pageDownloadProgressLabel")
        self.verticalLayout_4.addWidget(self.pageDownloadProgressLabel)
        self.pageDownloadProgressBar = QtWidgets.QProgressBar(self.widget_4)
        self.pageDownloadProgressBar.setMaximum(0)
        self.pageDownloadProgressBar.setProperty("value", -1)
        self.pageDownloadProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pageDownloadProgressBar.setObjectName("pageDownloadProgressBar")
        self.verticalLayout_4.addWidget(self.pageDownloadProgressBar)
        spacerItem8 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.compositingLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.compositingLabel.setFont(font)
        self.compositingLabel.setText("")
        self.compositingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.compositingLabel.setWordWrap(True)
        self.compositingLabel.setObjectName("compositingLabel")
        self.verticalLayout_4.addWidget(self.compositingLabel)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget_4, 0, 0, 1, 1)
        self.dynamicStack.addWidget(self.Download)
        self.mainvertical.addWidget(self.dynamicStack)
        self.gridLayout.addLayout(self.mainvertical, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTree = QtWidgets.QMenu(self.menubar)
        self.menuTree.setObjectName("menuTree")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuComposition = QtWidgets.QMenu(self.menuSetting)
        self.menuComposition.setTearOffEnabled(False)
        self.menuComposition.setSeparatorsCollapsible(False)
        self.menuComposition.setObjectName("menuComposition")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionJpg = QtWidgets.QAction(MainWindow)
        self.actionJpg.setObjectName("actionJpg")
        self.actionPdf = QtWidgets.QAction(MainWindow)
        self.actionPdf.setObjectName("actionPdf")
        self.actionKeep_originals = QtWidgets.QAction(MainWindow)
        self.actionKeep_originals.setCheckable(True)
        self.actionKeep_originals.setChecked(False)
        self.actionKeep_originals.setObjectName("actionKeep_originals")
        self.actionCompositeJpg = QtWidgets.QAction(MainWindow)
        self.actionCompositeJpg.setCheckable(True)
        self.actionCompositeJpg.setObjectName("actionCompositeJpg")
        self.actionCompositePdf = QtWidgets.QAction(MainWindow)
        self.actionCompositePdf.setCheckable(True)
        self.actionCompositePdf.setObjectName("actionCompositePdf")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionSettingsApply = QtWidgets.QAction(MainWindow)
        self.actionSettingsApply.setObjectName("actionSettingsApply")
        self.menuFile.addAction(self.actionExit)
        self.menuTree.addAction(self.actionGenerate)
        self.menuComposition.addAction(self.actionCompositeJpg)
        self.menuComposition.addAction(self.actionCompositePdf)
        self.menuSetting.addAction(self.menuComposition.menuAction())
        self.menuSetting.addAction(self.actionKeep_originals)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTree.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.dynamicStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manga Downloader"))
        self.searchNavButton.setText(_translate("MainWindow", "Search"))
        self.directNavButton.setText(_translate("MainWindow", "URL"))
        self.viewFunButton.setText(_translate("MainWindow", "Browser"))
        self.searchInputBox.setPlaceholderText(_translate("MainWindow", "Input manga name ..."))
        self.mangaSearchButton.setText(_translate("MainWindow", "Search"))
        item = self.searchResultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.searchResultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Latest Chapter"))
        self.searchNextButton.setText(_translate("MainWindow", "Next"))
        self.DirectTitle.setText(_translate("MainWindow", "Direct Url Download"))
        self.directDownloadInput.setPlaceholderText(_translate("MainWindow", "Input Url ..."))
        self.directNextButton.setText(_translate("MainWindow", "Next"))
        self.mangaTitle.setText(_translate("MainWindow", "Manga Dowload"))
        self.selectAllMangaButton.setText(_translate("MainWindow", "Select all"))
        self.inverseSelectedMangaButton.setText(_translate("MainWindow", "Inverse selection"))
        self.selectedMangaDownloadButton.setText(_translate("MainWindow", "Download"))
        self.totalDownloadProgressLabel.setText(_translate("MainWindow", "Total download"))
        self.totalDownloadProgressBar.setFormat(_translate("MainWindow", "%v of %m chapters | %p%"))
        self.chapterDownloadProgressLabel.setText(_translate("MainWindow", "Chapter download"))
        self.chapterDownloadProgressBar.setFormat(_translate("MainWindow", "%v of %m pages | %p%"))
        self.pageDownloadProgressLabel.setText(_translate("MainWindow", "Page download"))
        self.pageDownloadProgressBar.setFormat(_translate("MainWindow", "%v of %m bytes | %p%"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTree.setTitle(_translate("MainWindow", "Tree"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuComposition.setTitle(_translate("MainWindow", "Composition"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionJpg.setText(_translate("MainWindow", "Jpg"))
        self.actionPdf.setText(_translate("MainWindow", "Pdf"))
        self.actionKeep_originals.setText(_translate("MainWindow", "Keep originals"))
        self.actionCompositeJpg.setText(_translate("MainWindow", "Jpg"))
        self.actionCompositePdf.setText(_translate("MainWindow", "Pdf"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate"))
        self.actionSettingsApply.setText(_translate("MainWindow", "Apply"))
